CobotWebApp/Models/View/HomeViewModel.cs
using CobotWebApp.Models.View.Partial;

namespace CobotWebApp.Models.View
{
    public class HomeViewModel
    {
        public class DashboardViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
    }
}

CobotWebApp/Controllers/AdtController.cs
using CobotWebApp.Helper;
using CobotWebApp.Models;
using CobotWebApp.Models.View;
using CobotWebApp.Services;
using CobotWebApp.Singleton;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace CobotWebApp.Controllers
{
    [Authorize]
    public class AdtController : Controller
    {
        private readonly ILogger<AdtController> _logger;
        private readonly IBuildDependency _buildDependency;
        private readonly CobotAdtInitializeFunctionService _cobotAdtInitializeFunctionService;
        public AdtController(ILogger<AdtController> logger,
            IBuildDependency buildDependency,
            CobotAdtInitializeFunctionService cobotAdtInitializeFunctionService)
        {
            _logger = logger;
            _buildDependency = buildDependency;
            _cobotAdtInitializeFunctionService = cobotAdtInitializeFunctionService;


        }
        public IActionResult Index()
        {
            return Redirect("Adt/Dashboard");
        }
        public IActionResult Dashboard()
        {
            AdtViewModel.DashboardViewModel dashboardViewModel = new AdtViewModel.DashboardViewModel();
            AdtViewHelper.DashboardViewHelper dashboardViewHelper = new AdtViewHelper.DashboardViewHelper();
            dashboardViewModel.BreadCrumbPartialViewModelList = dashboardViewHelper.GetBreadCrumbPartialViewModelList();
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> UploadDtdlModelAsync()
        {
            AdtViewModel.UploadDtdlModelViewModel uploadDtdlModelViewModel = new AdtViewModel.UploadDtdlModelViewModel();
            AdtViewHelper.UploadDtdlModelViewHelper uploadDtdlModelViewHelper = new AdtViewHelper.UploadDtdlModelViewHelper(
                cobotAdtInitializeFunctionService: _cobotAdtInitializeFunctionService);
            uploadDtdlModelViewModel.BreadCrumbPartialViewModelList = uploadDtdlModelViewHelper.GetBreadCrumbPartialViewModelList();
            uploadDtdlModelViewModel.UploadDtdlModelResponseViewModelList = await uploadDtdlModelViewHelper.GetUploadDtdlModelResponseViewModelListAsync();
            return View(uploadDtdlModelViewModel);
        }
        public async Task<IActionResult> DeleteAdtRelationshipAsync()
        {
            AdtViewModel.DeleteAdtRelationshipViewModel deleteAdtRelationshipViewModel = new AdtViewModel.DeleteAdtRelationshipViewModel();
            AdtViewHelper.DeleteAdtRelationshipViewHelper deleteAdtRelationshipViewHelper = new AdtViewHelper.DeleteAdtRelationshipViewHelper(
                cobotAdtInitializeFunctionService: _cobotAdtInitializeFunctionService);
            deleteAdtRelationshipViewModel.BreadCrumbPartialViewModelList = deleteAdtRelationshipViewHelper.GetBreadCrumbPartialViewModelList();
            deleteAdtRelationshipViewModel.DeleteAdtRelationshipResponseViewModelList = await deleteAdtRelationshipViewHelper.GetDeleteAdtRelationshipResponseViewModelListAsync();
            return View(deleteAdtRelationshipViewModel);
        }
        public async Task<IActionResult> DeleteAdtModelAsync()
        {
            AdtViewModel.DeleteAdtModelViewModel deleteAdtModelViewModel = new AdtViewModel.DeleteAdtModelViewModel();
            AdtViewHelper.DeleteAdtModelViewHelper deleteAdtModelViewHelper = new AdtViewHelper.DeleteAdtModelViewHelper(
                cobotAdtInitializeFunctionService: _cobotAdtInitializeFunctionService);
            deleteAdtModelViewModel.BreadCrumbPartialViewModelList = deleteAdtModelViewHelper.GetBreadCrumbPartialViewModelList();
            deleteAdtModelViewModel.DeleteAdtModelResponseViewModelList = await deleteAdtModelViewHelper.GetDeleteAdtModelResponseViewModelListAsync();
            return View(deleteAdtModelViewModel);
        }
        public async Task<IActionResult> CreateAdtModelAsync()
        {
            AdtViewModel.CreateAdtModelViewModel createAdtModelViewModel = new AdtViewModel.CreateAdtModelViewModel();
            AdtViewHelper.CreateAdtModelViewHelper createAdtModelViewHelper = new AdtViewHelper.CreateAdtModelViewHelper(
                cobotAdtInitializeFunctionService: _cobotAdtInitializeFunctionService);
            createAdtModelViewModel.BreadCrumbPartialViewModelList = createAdtModelViewHelper.GetBreadCrumbPartialViewModelList();
            createAdtModelViewModel.CreateAdtModelResponseViewModelList = await createAdtModelViewHelper.GetCreateAdtModelResponseViewModelListAsync();
            return View(createAdtModelViewModel);
        }
        public async Task<IActionResult> CreateAdtRelationshipAsync()
        {
            AdtViewModel.CreateAdtRelationshipViewModel createAdtRelationshipViewModel = new AdtViewModel.CreateAdtRelationshipViewModel();
            AdtViewHelper.CreateAdtRelationshipViewHelper createAdtRelationshipViewHelper = new AdtViewHelper.CreateAdtRelationshipViewHelper(
                cobotAdtInitializeFunctionService: _cobotAdtInitializeFunctionService);
            createAdtRelationshipViewModel.BreadCrumbPartialViewModelList = createAdtRelationshipViewHelper.GetBreadCrumbPartialViewModelList();
            createAdtRelationshipViewModel.CreateAdtRelationshipResponseViewModelList = await createAdtRelationshipViewHelper.GetCreateAdtRelationshipResponseViewModelListAsync();
            return View(createAdtRelationshipViewModel);
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
        
    }
}

CobotWebApp/Controllers/IotController.cs
using CobotWebApp.Helper;
using CobotWebApp.Models.Request;
using CobotWebApp.Models.View;
using CobotWebApp.Services;
using CobotWebApp.Singleton;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace CobotWebApp.Controllers
{
    [Authorize]
    public class IotController : Controller
    {
        private readonly ILogger<IotController> _logger;
        private readonly IBuildDependency _buildDependency;
        private readonly CobotIotCommandFunctionService _cobotIotCommandFunctionService;
        public IotController(ILogger<IotController> logger,
            IBuildDependency buildDependency,
            CobotIotCommandFunctionService cobotIotCommandFunctionService)
        {
            _logger = logger;
            _buildDependency = buildDependency;
            _cobotIotCommandFunctionService = cobotIotCommandFunctionService;
        }
        public IActionResult Index()
        {
            return Redirect("Iot/Dashboard");
        }
        public IActionResult Dashboard()
        {
            IotViewHelper.DashboardViewHelper dashboardViewHelper = new IotViewHelper.DashboardViewHelper();
            IotViewModel.DashboardViewModel dashboardViewModel = new IotViewModel.DashboardViewModel();
            dashboardViewModel.BreadCrumbPartialViewModelList = dashboardViewHelper.GetBreadCrumbPartialViewModelList();
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> EnableControlCommandResponseAsync()
        {
            IotViewHelper.EnableControlCommandResponseViewHelper enableControlCommandResponseViewHelper = new IotViewHelper
                .EnableControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.EnableControlCommandResponseViewModel enableControlCommandResponseViewModel = new IotViewModel.EnableControlCommandResponseViewModel();
            enableControlCommandResponseViewModel.BreadCrumbPartialViewModelList = enableControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            enableControlCommandResponseViewModel.EnableControlCommandResponseModel = await enableControlCommandResponseViewHelper.PostEnableControlCommandResponseModelAsync();
            return View(enableControlCommandResponseViewModel);
        }
        public async Task<IActionResult> DisableControlCommandResponseAsync()
        {
            IotViewHelper.DisableControlCommandResponseViewHelper disableControlCommandResponseViewHelper = new IotViewHelper
                .DisableControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.DisableControlCommandResponseViewModel disableControlCommandResponseViewModel = new IotViewModel.DisableControlCommandResponseViewModel();
            disableControlCommandResponseViewModel.BreadCrumbPartialViewModelList = disableControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            disableControlCommandResponseViewModel.DisableControlCommandResponseModel = await disableControlCommandResponseViewHelper.PostDisableControlCommandResponseModelAsync();
            return View(disableControlCommandResponseViewModel);
        }
        public async Task<IActionResult> PowerOnControlCommandResponseAsync()
        {
            IotViewHelper.PowerOnControlCommandResponseViewHelper powerOnControlCommandResponseViewHelper = new IotViewHelper
                .PowerOnControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.PowerOnControlCommandResponseViewModel powerOnControlCommandResponseViewModel = new IotViewModel.PowerOnControlCommandResponseViewModel();
            powerOnControlCommandResponseViewModel.BreadCrumbPartialViewModelList = powerOnControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            powerOnControlCommandResponseViewModel.PowerOnControlCommandResponseModel = await powerOnControlCommandResponseViewHelper.PostPowerOnControlCommandResponseModelAsync();
            return View(powerOnControlCommandResponseViewModel);
        }
        public async Task<IActionResult> PowerOffControlCommandResponseAsync()
        {
            IotViewHelper.PowerOffControlCommandResponseViewHelper powerOffControlCommandResponseViewHelper = new IotViewHelper
                .PowerOffControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.PowerOffControlCommandResponseViewModel powerOffControlCommandResponseViewModel = new IotViewModel.PowerOffControlCommandResponseViewModel();
            powerOffControlCommandResponseViewModel.BreadCrumbPartialViewModelList = powerOffControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            powerOffControlCommandResponseViewModel.PowerOffControlCommandResponseModel = await powerOffControlCommandResponseViewHelper.PostPowerOffControlCommandResponseModelAsync();
            return View(powerOffControlCommandResponseViewModel);
        }
        public async Task<IActionResult> StartFreeDriveControlCommandResponseAsync()
        {
            IotViewHelper.StartFreeDriveControlCommandResponseViewHelper startFreeDriveControlCommandResponseViewHelper = new IotViewHelper
                .StartFreeDriveControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.StartFreeDriveControlCommandResponseViewModel startFreeDriveControlCommandResponseViewModel = new IotViewModel.StartFreeDriveControlCommandResponseViewModel();
            startFreeDriveControlCommandResponseViewModel.BreadCrumbPartialViewModelList = startFreeDriveControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            startFreeDriveControlCommandResponseViewModel.StartFreeDriveControlCommandResponseModel = await startFreeDriveControlCommandResponseViewHelper.PostStartFreeDriveControlCommandResponseModelAsync();
            return View(startFreeDriveControlCommandResponseViewModel);
        }
        public async Task<IActionResult> StopFreeDriveControlCommandResponseAsync()
        {
            IotViewHelper.StopFreeDriveControlCommandResponseViewHelper stopFreeDriveControlCommandResponseViewHelper = new IotViewHelper
                .StopFreeDriveControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.StopFreeDriveControlCommandResponseViewModel stopFreeDriveControlCommandResponseViewModel = new IotViewModel.StopFreeDriveControlCommandResponseViewModel();
            stopFreeDriveControlCommandResponseViewModel.BreadCrumbPartialViewModelList = stopFreeDriveControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            stopFreeDriveControlCommandResponseViewModel.StopFreeDriveControlCommandResponseModel = await stopFreeDriveControlCommandResponseViewHelper.PostStopFreeDriveControlCommandResponseModelAsync();
            return View(stopFreeDriveControlCommandResponseViewModel);
        }
        public async Task<IActionResult> PlayControlCommandResponseAsync()
        {
            IotViewHelper.PlayControlCommandResponseViewHelper playControlCommandResponseViewHelper = new IotViewHelper
                .PlayControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.PlayControlCommandResponseViewModel playControlCommandResponseViewModel = new IotViewModel.PlayControlCommandResponseViewModel();
            playControlCommandResponseViewModel.BreadCrumbPartialViewModelList = playControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            playControlCommandResponseViewModel.PlayControlCommandResponseModel = await playControlCommandResponseViewHelper.PostPlayControlCommandResponseModelAsync();
            return View(playControlCommandResponseViewModel);
        }
        public async Task<IActionResult> PauseControlCommandResponseAsync()
        {
            IotViewHelper.PauseControlCommandResponseViewHelper pauseControlCommandResponseViewHelper = new IotViewHelper
                .PauseControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.PauseControlCommandResponseViewModel pauseControlCommandResponseViewModel = new IotViewModel.PauseControlCommandResponseViewModel();
            pauseControlCommandResponseViewModel.BreadCrumbPartialViewModelList = pauseControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            pauseControlCommandResponseViewModel.PauseControlCommandResponseModel = await pauseControlCommandResponseViewHelper.PostPauseControlCommandResponseModelAsync();
            return View(pauseControlCommandResponseViewModel);
        }
        public async Task<IActionResult> CloseSafetyPopupControlCommandResponseAsync()
        {
            IotViewHelper.CloseSafetyPopupControlCommandResponseViewHelper closeSafetyPopupControlCommandResponseViewHelper = new IotViewHelper
                .CloseSafetyPopupControlCommandResponseViewHelper(cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            IotViewModel.CloseSafetyPopupControlCommandResponseViewModel closeSafetyPopupControlCommandResponseViewModel = new IotViewModel.CloseSafetyPopupControlCommandResponseViewModel();
            closeSafetyPopupControlCommandResponseViewModel.BreadCrumbPartialViewModelList = closeSafetyPopupControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelList();
            closeSafetyPopupControlCommandResponseViewModel.CloseSafetyPopupControlCommandResponseModel = await closeSafetyPopupControlCommandResponseViewHelper.PostCloseSafetyPopupControlCommandResponseModelAsync();
            return View(closeSafetyPopupControlCommandResponseViewModel);
        }

CobotWebApp/Views/Home/Dashboard.cshtml
@model CobotWebApp.Models.View.HomeViewModel.DashboardViewModel;

<div class="container">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="h2 pb-4 pt-2 d-flex flex-row" id="twinsDashboarditle">
            <div class="pe-2">
                <span>Home Dashboard</span>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            @*<div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Azure ADT</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Adt" asp-action="Dashboard">Open</a>
                    </div>
                </div>
            </div>*@
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Azure IOT</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Iot" asp-action="Dashboard">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Twins</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="Dashboard">Open</a>
                    </div>
                </div>
            </div>
           @* <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Time Series</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Dashboard">Open</a>
                    </div>
                </div>
            </div>*@
           @* <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Azure ADT Graph</h4>
                    </div>
                    <div class="card-body">
                        <button type="button" class="w-100 btn btn-lg btn-primary">Open</button>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Azure ADT 3D Scenes</h4>
                    </div>
                    <div class="card-body">
                        <button type="button" class="w-100 btn btn-lg btn-primary">Open</button>
                    </div>
                </div>
            </div>*@
        </div>
    </main>
    <partial name="_FooterPartial" />
</div>

@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
        vertical-align: -.125em;
        fill: currentColor;
         }
        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }

        .row [class*="col-"] {
            margin-bottom: -99999px;
            padding-bottom: 99999px;
        }

        .row {
            overflow: hidden;
        }

    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
}