CobotWebApp/Models/View/TwinsViewModel.cs
using CobotWebApp.Models.Request;
using CobotWebApp.Models.View.Partial;

namespace CobotWebApp.Models.View
{
    public class TwinsViewModel
    {
        public class DashboardViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class StartIotControlCommandResponseViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
            public List<CobotIotCommandFunctionModel.ResponseModel.StartIotControlCommandResponseModel>? StartIotControlCommandResponseModelList { get; set; }
        }
        public class StopIotControlCommandResponseViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
            public List<CobotIotCommandFunctionModel.ResponseModel.StopIotControlCommandResponseModel>? StopIotControlCommandResponseModelList { get; set; }
        }
        public class TwinsTelemetryViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class TwinsSimulationViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class TwinOfTwinViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class TwinsStatusViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
    }
}

CobotWebApp/Controllers/TwinsController.cs
using CobotWebApp.Helper;
using CobotWebApp.Models;
using CobotWebApp.Models.View;
using CobotWebApp.Singleton;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Azure;
using Azure.DigitalTwins.Core;
using Azure.Identity;
using CobotWebApp.Hubs;
using CobotWebApp.Services;

namespace CobotWebApp.Controllers
{
    [Authorize]
    public class TwinsController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBuildDependency _buildDependency;
        private readonly CobotIotCommandFunctionService _cobotIotCommandFunctionService;
        public TwinsController(ILogger<HomeController> logger,
            IBuildDependency buildDependency,
            CobotIotCommandFunctionService cobotIotCommandFunctionService)
        {
            _logger = logger;
            _buildDependency = buildDependency;
            _cobotIotCommandFunctionService = cobotIotCommandFunctionService;
        }
        public IActionResult Index()
        {
            return Redirect("/Twins/Dashboard");
        }
        public IActionResult Dashboard()
        {
            TwinsViewModel.DashboardViewModel dashboardViewModel = new TwinsViewModel.DashboardViewModel();
            TwinsViewHelper.DashboardViewHelper dashboardViewHelper = new TwinsViewHelper.DashboardViewHelper();
            dashboardViewModel.BreadCrumbPartialViewModelList = dashboardViewHelper.GetBreadCrumbPartialViewModelListForDashboardView();
            return View(dashboardViewModel);
        }
        public async Task<IActionResult> StartIotControlCommandResponseAsync(
            bool cobotSwitchCheckDefault,
            bool controlBoxSwitchCheckDefault,
            bool payloadSwitchCheckDefault,
            bool baseSwitchCheckDefault,
            bool elbowSwitchCheckDefault,
            bool shoulderSwitchCheckDefault,
            bool wrist1SwitchCheckDefault,
            bool wrist2SwitchCheckDefault,
            bool wrist3SwitchCheckDefault,
            bool toolSwitchCheckDefault)
        {
            TwinsViewModel.StartIotControlCommandResponseViewModel startIotControlCommandResponseViewModel = new TwinsViewModel.StartIotControlCommandResponseViewModel();
            TwinsViewHelper.StartIotControlCommandResponseViewHelper startIotControlCommandResponseViewHelper = new TwinsViewHelper.StartIotControlCommandResponseViewHelper(
                cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            startIotControlCommandResponseViewModel.BreadCrumbPartialViewModelList = startIotControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForStartIotControlCommandResponseView();
            startIotControlCommandResponseViewModel.StartIotControlCommandResponseModelList = await startIotControlCommandResponseViewHelper.PostStartIotControlCommandResponseModelListAsync(
                cobotSwitchCheckDefault: cobotSwitchCheckDefault,
                controlBoxSwitchCheckDefault: controlBoxSwitchCheckDefault,
                payloadSwitchCheckDefault: payloadSwitchCheckDefault,
                baseSwitchCheckDefault: baseSwitchCheckDefault,
                elbowSwitchCheckDefault: elbowSwitchCheckDefault,
                shoulderSwitchCheckDefault: shoulderSwitchCheckDefault,
                wrist1SwitchCheckDefault: wrist1SwitchCheckDefault,
                wrist2SwitchCheckDefault: wrist2SwitchCheckDefault,
                wrist3SwitchCheckDefault: wrist3SwitchCheckDefault,
                toolSwitchCheckDefault: toolSwitchCheckDefault);
            return View(startIotControlCommandResponseViewModel);
        }
        public async Task<IActionResult> StopIotControlCommandResponseAsync()
        {
            TwinsViewModel.StopIotControlCommandResponseViewModel stopIotControlCommandResponseViewModel = new TwinsViewModel.StopIotControlCommandResponseViewModel();
            TwinsViewHelper.StopIotControlCommandResponseViewHelper stopIotControlCommandResponseViewHelper = new TwinsViewHelper.StopIotControlCommandResponseViewHelper(
                cobotIotCommandFunctionService: _cobotIotCommandFunctionService);
            stopIotControlCommandResponseViewModel.BreadCrumbPartialViewModelList = stopIotControlCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForStopIotControlCommandResponseView();
            stopIotControlCommandResponseViewModel.StopIotControlCommandResponseModelList = await stopIotControlCommandResponseViewHelper.PostStopIotControlCommandResponseModelListAsync();
            return View(stopIotControlCommandResponseViewModel);
        }
        public IActionResult TwinsTelemetryAsync()
        {
            TwinsViewModel.TwinsTelemetryViewModel twinsTelemetryCommandResponseViewModel = new TwinsViewModel.TwinsTelemetryViewModel();
            TwinsViewHelper.TwinsTelemetryViewHelper twinsTelemetryCommandResponseViewHelper = new TwinsViewHelper.TwinsTelemetryViewHelper();
            twinsTelemetryCommandResponseViewModel.BreadCrumbPartialViewModelList = twinsTelemetryCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForTwinsTelemetryView();
            return View(twinsTelemetryCommandResponseViewModel);
        }
        public IActionResult TwinsSimulationAsync()
        {
            TwinsViewModel.TwinsSimulationViewModel twinsSimulationCommandResponseViewModel = new TwinsViewModel.TwinsSimulationViewModel();
            TwinsViewHelper.TwinsSimulationViewHelper twinsSimulationCommandResponseViewHelper = new TwinsViewHelper.TwinsSimulationViewHelper();
            twinsSimulationCommandResponseViewModel.BreadCrumbPartialViewModelList = twinsSimulationCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForTwinsSimulationView();
            return View(twinsSimulationCommandResponseViewModel);
        }
        public IActionResult TwinOfTwin()
        {
            TwinsViewModel.TwinOfTwinViewModel twinOfTwinViewModel = new TwinsViewModel.TwinOfTwinViewModel();
            TwinsViewHelper.TwinOfTwinViewHelper twinOfTwinCommandResponseViewHelper = new TwinsViewHelper.TwinOfTwinViewHelper();
            twinOfTwinViewModel.BreadCrumbPartialViewModelList = twinOfTwinCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForTwinOfTwinView();
            return View(twinOfTwinViewModel);
        }
        public IActionResult TwinsStatus()
        {
            TwinsViewModel.TwinsStatusViewModel twinsStatusViewModel = new TwinsViewModel.TwinsStatusViewModel();
            TwinsViewHelper.TwinsStatusViewHelper twinOfTwinCommandResponseViewHelper = new TwinsViewHelper.TwinsStatusViewHelper();
            twinsStatusViewModel.BreadCrumbPartialViewModelList = twinOfTwinCommandResponseViewHelper.GetBreadCrumbPartialViewModelListForTwinsStatusView();
            return View(twinsStatusViewModel);
        }
    }
}

CobotWebApp/Views/Twins/Dashboard.cshtml
@model CobotWebApp.Models.View.TwinsViewModel.DashboardViewModel;

<div class="container">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="h2 pb-4 pt-2 d-flex flex-row" id="twinsDashboarditle">
            <div class="pe-2">
                <span>Twins Dashboard</span>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
           @* <div class="col">
                <div class="card rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Start IOT</h4>
                    </div>
                    <div class="card-body">
                        <button type="button" class="w-100 btn btn-lg btn-primary" data-bs-toggle="modal" data-bs-target="#exampleModal">
                            Open
                        </button>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Stop IOT</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-danger" asp-controller="Twins" asp-action="StopIotControlCommandResponse">Execute</a>
                    </div>
                </div>
            </div>*@
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Twins Telemetry</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="TwinsTelemetry">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Twins Simulation</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="TwinsSimulation">Open</a>
                    </div>
                </div>
            </div>
          @*  <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Twin Of Twin</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="TwinOfTwin">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Twins Status</h4>
                    </div>
                    <div class="card-body">
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="TwinsStatus">Open</a>
                    </div>
                </div>
            </div>*@
        </div>
    </main>
    <partial name="_FooterPartial" />
</div>
<div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog">
        <form action="/Twins/StartIotControlCommandResponse" method="get">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="exampleModalLabel">IOT Devices</h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="cobotCheckbox">Cobot</label>
                        <input class="form-check-input" type="checkbox" id="cobotCheckbox" name="cobotSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="controlBoxCheckbox">Control Box</label>
                        <input class="form-check-input" type="checkbox" id="controlBoxCheckbox" name="controlBoxSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="payloadCheckbox">Payload</label>
                        <input class="form-check-input" type="checkbox" id="payloadCheckbox" name="payloadSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="baseCheckbox">Base</label>
                        <input class="form-check-input" type="checkbox" id="baseCheckbox" name="baseSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="shoulderCheckbox">Shoulder</label>
                        <input class="form-check-input" type="checkbox" id="shoulderCheckbox" name="shoulderSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="elbowCheckbox">Elbow</label>
                        <input class="form-check-input" type="checkbox" id="elbowCheckbox" name="elbowSwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="wrist1Checkbox">Wrist1</label>
                        <input class="form-check-input" type="checkbox" id="wrist1Checkbox" name="wrist1SwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="wrist2Checkbox">Wrist2</label>
                        <input class="form-check-input" type="checkbox" id="wrist2Checkbox" name="wrist2SwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch pb-3">
                        <label class="form-check-label" for="wrist3Checkbox">Wrist3</label>
                        <input class="form-check-input" type="checkbox" id="wrist3Checkbox" name="wrist3SwitchCheckDefault" value="true" checked>
                    </div>
                    <div class="form-check form-switch">
                        <label class="form-check-label" for="toolCheckbox">Tool</label>
                        <input class="form-check-input" type="checkbox" id="toolCheckbox" name="toolSwitchCheckDefault" value="true" checked>
                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="submit" class="btn btn-danger">Execute</button>
                </div>
            </div>
        </form>
    </div>
</div>
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
}

CobotWebApp/Views/Twins/StartIotControlCommandResponse.cshtml
@using CobotWebApp.Models.Request;
@using static CobotWebApp.Models.View.TwinsViewModel.StartIotControlCommandResponseViewModel;
@using static CobotWebApp.Models.Request.CobotIotCommandFunctionModel;
@model CobotWebApp.Models.View.TwinsViewModel.StartIotControlCommandResponseViewModel;

<div class="container py-3">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        @if(Model.StartIotControlCommandResponseModelList is not null){
         <div class="row row-cols-1 row-cols-md-12 mb-3 text-center">
                <div class="col">
                    <div class="card mb-4 rounded-3 shadow-sm">
                        <div class="card-header py-3">
                            <h4 class="my-0 fw-normal">Start IOT</h4>
                        </div>
                        <div class="card-body">
                            <h1 class="card-title pricing-card-title">@Model.StartIotControlCommandResponseModelList.Count()<small class="text-body-secondary fw-light">/devices</small></h1>
                            <h1 class="card-title pricing-card-title">@Model.StartIotControlCommandResponseModelList.Sum(model => model.Duration)<small class="text-body-secondary fw-light">/ms</small></h1>
                            <div class="gap-4 pt-md-3 pb-md-3 mt-4 align-items-center justify-content-center">
                                <div class="list-group">
                                    @foreach (CobotIotCommandFunctionModel.ResponseModel.StartIotControlCommandResponseModel startIotControlCommandResponseModel in Model.StartIotControlCommandResponseModelList)
                                    {
                                        @if (startIotControlCommandResponseModel.CommandRequest is not null)
                                        {
                                            if (startIotControlCommandResponseModel.CommandResponse is not null &&
                                                startIotControlCommandResponseModel.CommandResponse.Payload is not null)
                                            {
                                                <div class="list-group-item list-group-item-action d-flex gap-3 py-3" aria-current="true">
                                                    @if (startIotControlCommandResponseModel.CommandResponse.Payload.Status is not null &&
                                                   startIotControlCommandResponseModel.CommandResponse.Payload.Status.Equals("COBOT_CLIENT_EXECUTED"))
                                                    {
                                                        <i class="bi bi-check-lg rounded-circle flex-shrink-0"></i>
                                                    }
                                                    else
                                                    {
                                                        <i class="bi bi-x-lg rounded-check flex-shrink-0"></i>
                                                    }

                                                    <div class="d-flex gap-2 w-100 justify-content-between">
                                                        <div>
                                                            <h6 class="mb-0 text-start">Name:@startIotControlCommandResponseModel.CommandRequest.DeviceId</h6>
                                                            <p class="mb-0 opacity-75 text-start">Status: @startIotControlCommandResponseModel.CommandResponse.Payload.Status Cobot Execution Duration: @startIotControlCommandResponseModel.CommandResponse.Payload.Duration/ms</p>
                                                        </div>
                                                        <small class="opacity-50 text-nowrap">@startIotControlCommandResponseModel.Duration/ms</small>
                                                    </div>
                                                </div>
                                            }
                                        }
                                    }
                                </div>
                            </div>

                            <a class="w-100 btn btn-lg btn-primary" asp-controller="Twins" asp-action="Dashboard">Back</a>
                        </div>
                    </div>
                </div>
            </div>
        }
     </main>
</div>

@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
}

CobotWebApp/Views/Twins/TwinsSimulation.cshtml
@model CobotWebApp.Models.View.TwinsViewModel.TwinsSimulationViewModel;

<div class="container py-3">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="container" id="icon-grid">
            <div class="h2 py-3 d-flex flex-row" id="twinsSimulationTitle">
                <div class="pe-2">
                    <span>Twins Simulation</span> (<span id="twinsSimulationElapsedSpan">Loading</span><small class="text-body-secondary fw-light">/ms</small>)
                </div>
                <div>
                     <span class="spinner-border text-primary" id="twinsSimulationSpinner" style="display: block" role="status">
                        <span class="visually-hidden">Loading...</span>
                    </span>
               </div>
            </div>
            <div class="py-3">
                <div class="pe-2">
                    <span class="h3">Elbow Simulation</span>
                </div>
                <div id="elbowGraphDiv" style="width:100%;height:650px"></div>
            </div>
            <div class="py-3">
                <div class="pe-2">
                    <span class="h3">Tool Simulation</span>
                </div>
                <div id="toolGraphDiv" style="width:100%;height:650px"></div>
            </div>
            <a class="w-100 btn btn-lg btn-primary mt-3" asp-controller="Twins" asp-action="Dashboard">Back</a>
        </div>
    </main>
</div>
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
    <script src="/js/jquery/ajax.googleapis.com_ajax_libs_jquery_1.12.4_jquery.min.js"></script>
    <script src="/js/plotly/cdn.plot.ly_plotly-latest.min.js"></script>
    <script src="/js/signalr/dist/browser/signalr.js"></script>
    <script src="/js/twins-simulation-task.js"></script>
}