CobotWebApp/Models/View/TimeseriesViewModel.cs
using CobotWebApp.Models.View.Partial;

namespace CobotWebApp.Models.View
{
    public class TimeseriesViewModel
    {
        public class DashboardViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class CobotViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class ControlBoxViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class PayloadViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class BaseViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class ShoulderViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class ElbowViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class Wrist1ViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class Wrist2ViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class Wrist3ViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
        public class ToolViewModel
        {
            public List<BreadCrumbPartialViewModel>? BreadCrumbPartialViewModelList { get; set; }
        }
    }
}

CobotWebApp/Controllers/TimeseriesController.cs
using CobotWebApp.Helper;
using CobotWebApp.Models;
using CobotWebApp.Models.View;
using CobotWebApp.Singleton;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;
using Azure;
using Azure.DigitalTwins.Core;
using Azure.Identity;
using CobotWebApp.Hubs;
using CobotWebApp.Services;

namespace CobotWebApp.Controllers
{
    [Authorize]
    public class TimeseriesController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IBuildDependency _buildDependency;
        private readonly CobotIotCommandFunctionService _cobotIotCommandFunctionService;
        public TimeseriesController(ILogger<HomeController> logger,
            IBuildDependency buildDependency,
            CobotIotCommandFunctionService cobotIotCommandFunctionService)
        {
            _logger = logger;
            _buildDependency = buildDependency;
            _cobotIotCommandFunctionService = cobotIotCommandFunctionService;
        }
        public IActionResult Index()
        {
            return Redirect("/Timeseries/Dashboard");
        }
        public IActionResult Dashboard()
        {
            TimeseriesViewModel.DashboardViewModel dashboardViewModel = new TimeseriesViewModel.DashboardViewModel();
            TimeseriesViewHelper.DashboardViewHelper dashboardViewHelper = new TimeseriesViewHelper.DashboardViewHelper();
            dashboardViewModel.BreadCrumbPartialViewModelList = dashboardViewHelper.GetBreadCrumbPartialViewModelListForDashboardView();
            return View(dashboardViewModel);
        }
        public IActionResult Cobot()
        {
            TimeseriesViewModel.CobotViewModel cobotViewModel = new TimeseriesViewModel.CobotViewModel();
            TimeseriesViewHelper.CobotViewHelper cobotViewHelper = new TimeseriesViewHelper.CobotViewHelper();
            cobotViewModel.BreadCrumbPartialViewModelList = cobotViewHelper.GetBreadCrumbPartialViewModelListForCobotView();
            return View(cobotViewModel);
        }
        public IActionResult ControlBox()
        {
            TimeseriesViewModel.ControlBoxViewModel controlBoxViewModel = new TimeseriesViewModel.ControlBoxViewModel();
            TimeseriesViewHelper.ControlBoxViewHelper controlBoxViewHelper = new TimeseriesViewHelper.ControlBoxViewHelper();
            controlBoxViewModel.BreadCrumbPartialViewModelList = controlBoxViewHelper.GetBreadCrumbPartialViewModelListForCobotView();
            return View(controlBoxViewModel);
        }
        public IActionResult Payload()
        {
            TimeseriesViewModel.PayloadViewModel payloadViewModel = new TimeseriesViewModel.PayloadViewModel();
            TimeseriesViewHelper.PayloadViewHelper payloadViewHelper = new TimeseriesViewHelper.PayloadViewHelper();
            payloadViewModel.BreadCrumbPartialViewModelList = payloadViewHelper.GetBreadCrumbPartialViewModelListForPayloadView();
            return View(payloadViewModel);
        }
        public IActionResult Base()
        {
            TimeseriesViewModel.BaseViewModel baseViewModel = new TimeseriesViewModel.BaseViewModel();
            TimeseriesViewHelper.BaseViewHelper baseViewHelper = new TimeseriesViewHelper.BaseViewHelper();
            baseViewModel.BreadCrumbPartialViewModelList = baseViewHelper.GetBreadCrumbPartialViewModelListForBaseView();
            return View(baseViewModel);
        }
        public IActionResult Shoulder()
        {
            TimeseriesViewModel.ShoulderViewModel shoulderViewModel = new TimeseriesViewModel.ShoulderViewModel();
            TimeseriesViewHelper.ShoulderViewHelper shoulderViewHelper = new TimeseriesViewHelper.ShoulderViewHelper();
            shoulderViewModel.BreadCrumbPartialViewModelList = shoulderViewHelper.GetBreadCrumbPartialViewModelListForShoulderView();
            return View(shoulderViewModel);
        }
        public IActionResult Elbow()
        {
            TimeseriesViewModel.ElbowViewModel elbowViewModel = new TimeseriesViewModel.ElbowViewModel();
            TimeseriesViewHelper.ElbowViewHelper elbowViewHelper = new TimeseriesViewHelper.ElbowViewHelper();
            elbowViewModel.BreadCrumbPartialViewModelList = elbowViewHelper.GetBreadCrumbPartialViewModelListForElbowView();
            return View(elbowViewModel);
        }
        public IActionResult Wrist1()
        {
            TimeseriesViewModel.Wrist1ViewModel wrist1ViewModel = new TimeseriesViewModel.Wrist1ViewModel();
            TimeseriesViewHelper.Wrist1ViewHelper wrist1ViewHelper = new TimeseriesViewHelper.Wrist1ViewHelper();
            wrist1ViewModel.BreadCrumbPartialViewModelList = wrist1ViewHelper.GetBreadCrumbPartialViewModelListForWrist1View();
            return View(wrist1ViewModel);
        }
        public IActionResult Wrist2()
        {
            TimeseriesViewModel.Wrist2ViewModel wrist2ViewModel = new TimeseriesViewModel.Wrist2ViewModel();
            TimeseriesViewHelper.Wrist2ViewHelper wrist2ViewHelper = new TimeseriesViewHelper.Wrist2ViewHelper();
            wrist2ViewModel.BreadCrumbPartialViewModelList = wrist2ViewHelper.GetBreadCrumbPartialViewModelListForWrist2View();
            return View(wrist2ViewModel);
        }
        public IActionResult Wrist3()
        {
            TimeseriesViewModel.Wrist3ViewModel wrist3ViewModel = new TimeseriesViewModel.Wrist3ViewModel();
            TimeseriesViewHelper.Wrist3ViewHelper wrist3ViewHelper = new TimeseriesViewHelper.Wrist3ViewHelper();
            wrist3ViewModel.BreadCrumbPartialViewModelList = wrist3ViewHelper.GetBreadCrumbPartialViewModelListForWrist3View();
            return View(wrist3ViewModel);
        }
        public IActionResult Tool()
        {
            TimeseriesViewModel.ToolViewModel toolViewModel = new TimeseriesViewModel.ToolViewModel();
            TimeseriesViewHelper.ToolViewHelper toolViewHelper = new TimeseriesViewHelper.ToolViewHelper();
            toolViewModel.BreadCrumbPartialViewModelList = toolViewHelper.GetBreadCrumbPartialViewModelListForToolView();
            return View(toolViewModel);
        }
    }
}

CobotWebApp/Views/Timeseries/Base.cshtml
@model CobotWebApp.Models.View.TimeseriesViewModel.BaseViewModel;

<div class="container py-3">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="h2 pb-4 pt-2 d-flex flex-row">
            <div class="pe-2">
                <span>Base</span> (<span id="timeseriesBaseElapsedSpan">Loading</span><small class="text-body-secondary fw-light">/ms</small>)
            </div>
            <div>
                <span class="spinner-border text-primary" id="timeseriesBaseSpinner" style="display: block" role="status">
                    <span class="visually-hidden">Loading...</span>
                </span>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3">
            <div class="pe-2">
                <span class="h3">Temperature</span>
            </div>
            <div id="baseTemperatureGraphDiv" style="width:100%;height:350px"></div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3">
            <div class="pe-2">
                <span class="h3">Position</span>
            </div>
            <div id="basePositionGraphDiv" style="width:100%;height:350px"></div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3">
            <div class="pe-2">
                <span class="h3">Voltage</span>
            </div>
            <div id="baseVoltageGraphDiv" style="width:100%;height:350px"></div>
        </div>
    </main>
</div>
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
    <script src="/js/jquery/ajax.googleapis.com_ajax_libs_jquery_1.12.4_jquery.min.js"></script>
    <script src="/js/plotly/cdn.plot.ly_plotly-latest.min.js"></script>
    <script src="/js/signalr/dist/browser/signalr.js"></script>
    <script src="/js/timeseries-base-task.js"></script>
}

CobotWebApp/Views/Timeseries/Cobot.cshtml
@model CobotWebApp.Models.View.TimeseriesViewModel.CobotViewModel;

<div class="container py-3">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="h2 pb-4 pt-2 d-flex flex-row">
            <div class="pe-2">
                <span>Cobot</span> (<span id="timeseriesCobotElapsedSpan">Loading</span><small class="text-body-secondary fw-light">/ms</small>)
            </div>
            <div>
                <span class="spinner-border text-primary" id="timeseriesCobotSpinner" style="display: block" role="status">
                    <span class="visually-hidden">Loading...</span>
                </span>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3">
            <div class="pe-2">
                <span class="h3">Elapsed Time</span>
            </div>
            <div id="cobotElapsedTimeGraphDiv" style="width:100%;height:350px"></div>
        </div>
    </main>
</div>
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
    <script src="/js/jquery/ajax.googleapis.com_ajax_libs_jquery_1.12.4_jquery.min.js"></script>
    <script src="/js/plotly/cdn.plot.ly_plotly-latest.min.js"></script>
    <script src="/js/signalr/dist/browser/signalr.js"></script>
    <script src="/js/timeseries-cobot-task.js"></script>
}

CobotWebApp/Views/Timeseries/Dashboard.cshtml
@model CobotWebApp.Models.View.TimeseriesViewModel.DashboardViewModel;

<div class="container">
    <partial name="_HeaderPartial" />
    <main>
        @await Html.PartialAsync("_BreadCrumbPartial", Model.BreadCrumbPartialViewModelList)
        <div class="h2 pb-4 pt-2 d-flex flex-row" id="twinsDashboarditle">
            <div class="pe-2">
                <span>Time Series Dashboard</span> (<span id="timeseriesDashboardElapsedSpan">Loading</span><small class="text-body-secondary fw-light">/ms</small>)
            </div>
            <div>
                <span class="spinner-border text-primary" id="timeseriesDashboardSpinner" style="display: block" role="status">
                    <span class="visually-hidden">Loading...</span>
                </span>
            </div>
        </div>
        <div class="row row-cols-1 row-cols-md-3 mb-3 text-center">
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Cobot</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="cobotStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Cobot">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Control Box</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="controlBoxStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="ControlBox">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Payload</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="payloadStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Payload">Open</a>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Base</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="baseStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Base">Open</a>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Shoulder</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="shoulderStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Shoulder">Open</a>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Elbow</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="elbowStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Elbow">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Wrist1</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="wrist1StatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Wrist1">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Wrist2</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="wrist2StatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Wrist2">Open</a>
                    </div>
                </div>
            </div>
            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Wrist3</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="wrist3StatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Wrist3">Open</a>
                    </div>
                </div>
            </div>

            <div class="col">
                <div class="card mb-4 rounded-3 shadow-sm">
                    <div class="card-header py-3">
                        <h4 class="my-0 fw-normal">Tool</h4>
                    </div>
                    <div class="card-body">
                        <div class="mt-2 mb-4 ">
                            <div class="card-title pricing-card-title mb-4 h3" id="toolStatusLabelDiv">null</div>
                        </div>
                        <a class="w-100 btn btn-lg btn-primary" asp-controller="Timeseries" asp-action="Tool">Open</a>
                    </div>
                </div>
            </div>

        </div>
    </main>
    <partial name="_FooterPartial" />
</div>
@section CSS{
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.5/font/bootstrap-icons.css">
    <style>
        .bi {
            vertical-align: -.125em;
            fill: currentColor;
        }

        .icon-link > .bi {
            width: .75em;
            height: .75em;
        }
    </style>
    <svg xmlns="http://www.w3.org/2000/svg" class="d-none">
        <symbol id="aperture" fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" />
            <path d="M14.31 8l5.74 9.94M9.69 8h11.48M7.38 12l5.74-9.94M9.69 16L3.95 6.06M14.31 16H2.83m13.79-4l-5.74 9.94" />
        </symbol>
        <symbol id="cart" viewBox="0 0 16 16">
            <path d="M0 1.5A.5.5 0 0 1 .5 1H2a.5.5 0 0 1 .485.379L2.89 3H14.5a.5.5 0 0 1 .49.598l-1 5a.5.5 0 0 1-.465.401l-9.397.472L4.415 11H13a.5.5 0 0 1 0 1H4a.5.5 0 0 1-.491-.408L2.01 3.607 1.61 2H.5a.5.5 0 0 1-.5-.5zM3.102 4l.84 4.479 9.144-.459L13.89 4H3.102zM5 12a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm7 0a2 2 0 1 0 0 4 2 2 0 0 0 0-4zm-7 1a1 1 0 1 1 0 2 1 1 0 0 1 0-2zm7 0a1 1 0 1 1 0 2 1 1 0 0 1 0-2z" />
        </symbol>
        <symbol id="chevron-right" viewBox="0 0 16 16">
            <path fill-rule="evenodd" d="M4.646 1.646a.5.5 0 0 1 .708 0l6 6a.5.5 0 0 1 0 .708l-6 6a.5.5 0 0 1-.708-.708L10.293 8 4.646 2.354a.5.5 0 0 1 0-.708z" />
        </symbol>
        <symbol id="house-door-fill" viewBox="0 0 16 16">
            <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z" />
        </symbol>
    </svg>
}
@section Scripts{
    <script src="/js/signalr/dist/browser/signalr.js"></script>
    <script src="/js/timeseries-dashboard-task.js"></script>
}